export const groupsHomeEnNZ = {
  'groupsHome.summary.title': 'Groups',
  'groupsHome.summary.view_all_accessibility': 'View all groups',
  'groupsHome.summary.view_all': 'View all',
  'groupsHome.summary.risk.safe': 'On track',
  'groupsHome.summary.risk.at_risk': 'Needs attention',
  'groupsHome.summary.risk.critical': 'Critical',
  'groupsHome.summary.risk.failed': 'Ended',
  'groupsHome.summary.risk.expired': 'Archived',
  'groupsHome.count.members': '{count} members',
  'groupsHome.count.members.one': '{count} member',
  'groupsHome.count.members.other': '{count} members',
  'groupsHome.count.streak': '{count} days streak',
  'groupsHome.count.streak.one': '{count} day streak',
  'groupsHome.count.streak.other': '{count} days streak',
  'groupsHome.summary.meta': '{members} - {streak} · {risk}',
  'groupsHome.invites.title': 'Open invites',
  'groupsHome.invites.hide_accessibility': 'Hide open invites',
  'groupsHome.invites.browse_accessibility': 'Browse open invites',
  'groupsHome.invites.hide': 'Hide',
  'groupsHome.invites.browse': 'Browse',
  'groupsHome.invites.type.group': 'group',
  'groupsHome.invites.type.promise': 'promise',
  'groupsHome.invites.saved_title': 'Saved {type} invite',
  'groupsHome.invites.saved_detail':
    'We saved code {code} on this phone. Open it again, or clear it if the invite no longer works.',
  'groupsHome.invites.open_saved': 'Open saved invite',
  'groupsHome.invites.clear': 'Clear',
  'groupsHome.invites.row_meta': '{members} - {streak}',
  'groupsHome.invites.empty_title': 'No public groups',
  'groupsHome.invites.empty_detail':
    'Check again, join with a code, or make a personal promise.',
  'groupsHome.invites.check_again': 'Check again',
  'groupsHome.invites.join_code': 'Join with code',
  'groupsHome.invites.personal_promise': 'Make a personal promise',
  'groupsHome.groupAction.title': 'For your groups',
  'groupsHome.groupAction.waiting': '{count} waiting',
  'groupsHome.groupAction.waiting.one': '{count} waiting',
  'groupsHome.groupAction.waiting.other': '{count} waiting',
  'groupsHome.groupAction.review_named': 'Review {possessiveName} proof',
  'groupsHome.groupAction.review': 'Review proof',
  'groupsHome.groupAction.review_group_meta':
    '{group} · Check it against the promise',
  'groupsHome.groupAction.review_meta': 'Check it against the promise',
  'groupsHome.groupAction.review_action': 'Review',
  'groupsHome.groupAction.pressure_named': '{group} needs a check-in',
  'groupsHome.groupAction.pressure_detail':
    'Open the group to see what is still due.',
  'groupsHome.groupAction.open_action': 'Open',
  'groupsHome.groupAction.empty_title': 'No reviews waiting',
  'groupsHome.groupAction.empty_detail':
    'No one is waiting for your review right now.',
} as const;
