/** Copy for the shared "not enough Momenta" sheet, the Momenta guide and the Pro journey. */
export const momentaTopUpEnNZ = {
  'commerce.topUp.toGo': '{amount} Momenta to go',
  'commerce.topUp.getMore': 'Get more Momenta',
  'commerce.topUp.inAndToGo': '+{credited} in. {remaining} to go.',
  'commerce.topUp.waits.promise': 'Pick a way. Your promise waits here.',
  'commerce.topUp.waits.group': 'Pick a way. Your group waits here.',
  'commerce.topUp.waits.join': 'Pick a way. You can join right after.',
  'commerce.topUp.waits.general': 'Pick a way to top up.',
  'commerce.topUp.oneMoreAd': 'One more ad and you’re there.',
  'commerce.topUp.moreAds': '{count} more ads and you’re there.',
  'commerce.topUp.adsResting':
    'Ads are resting for now. Pro or a quick review gets you there.',
  'commerce.topUp.youHave': 'You have {amount}',
  'commerce.topUp.need.promise': 'New promise · {amount}',
  'commerce.topUp.need.group': 'New group · {amount}',
  'commerce.topUp.need.join': 'Joining · {amount}',
  'commerce.topUp.need.general': 'Needed · {amount}',
  'commerce.topUp.watchTitle': 'Watch a short ad',
  'commerce.topUp.watchAnotherTitle': 'Watch another',
  'commerce.topUp.watchDetail': 'About 30 seconds',
  'commerce.topUp.watchReadyIn': 'Next one ready in {time}',
  'commerce.topUp.watchAnotherIn': 'Watch another in {time}',
  'commerce.topUp.watchCooldown':
    'The next one is ready in a couple of minutes',
  'commerce.topUp.watchDailyLimit': 'That’s all for today. More tomorrow.',
  'commerce.topUp.proTitle': 'Go Pro',
  'commerce.topUp.proDetail': '{amount} Momenta a week, no ad breaks',
  'commerce.topUp.reviewTitle': 'Check a friend’s proof',
  'commerce.topUp.reviewDetail': '+{amount} for each proof you check',
  'commerce.topUp.watchCta': 'Watch and get {amount}',
  'commerce.topUp.proCta': 'Go Pro',
  'commerce.topUp.proHint': 'You’ll see weekly and yearly plans next.',
  'commerce.topUp.reviewCta': 'Check proof',
  'commerce.topUp.whatAre': 'What are Momenta?',
  'commerce.topUp.notNow': 'Not now',
  'commerce.topUp.adding': 'Adding your Momenta',
  'commerce.topUp.addingDetail':
    'Checking the ad with the store. Usually a second or two.',
  'commerce.topUp.addingCta': 'Adding Momenta…',
  'commerce.topUp.safeToClose':
    'It’s safe to close this. Your Momenta still arrive.',
  'commerce.topUp.allSet': 'You’re all set',
  'commerce.topUp.allSet.promise': 'You have enough to start your promise.',
  'commerce.topUp.allSet.group': 'You have enough to start your group.',
  'commerce.topUp.allSet.join': 'You have enough to join.',
  'commerce.topUp.allSet.general': 'Your Momenta are in your balance.',
  'commerce.topUp.fromAds': 'From ads you watched',
  'commerce.topUp.addedNow': 'Added just now',
  'commerce.topUp.back.promise': 'Back to my promise',
  'commerce.topUp.back.group': 'Back to my group',
  'commerce.topUp.back.join': 'Back to joining',
  'commerce.topUp.back.general': 'Done',
  'commerce.topUp.costs': 'COSTS',
  'commerce.topUp.leftAfter': 'LEFT AFTER',
  'commerce.topUp.youHaveLabel': 'YOU HAVE',
  'commerce.topUp.amount': '{amount} Momenta',
  'commerce.topUp.leftOf': '{left} of {balance}',
  'commerce.topUp.getAmountMore': 'Get {amount} more Momenta',
  'commerce.topUp.shortBubble':
    'We’re {amount} Momenta short. I’ll keep this safe while you top up.',
  'commerce.momentaGuide.close': 'Close',
  'commerce.momentaGuide.forTitle': 'Momenta make a promise count',
  'commerce.momentaGuide.forBody':
    'Starting something new costs a little, so every promise is one you mean.',
  'commerce.momentaGuide.promise': 'Start a promise',
  'commerce.momentaGuide.group': 'Start a group',
  'commerce.momentaGuide.join': 'Join someone’s promise or group',
  'commerce.momentaGuide.firstFree': 'Your first one is free',
  'commerce.momentaGuide.firstJoinFree': 'Your first join is free',
  'commerce.momentaGuide.free': 'Proof, reviews and streaks',
  'commerce.momentaGuide.alwaysFree': 'Always free',
  'commerce.momentaGuide.freeValue': 'Free',
  'commerce.momentaGuide.howCta': 'How do I get them?',
  'commerce.momentaGuide.earnTitle': 'You earn them by showing up',
  'commerce.momentaGuide.earnBody':
    'Most Momenta come from keeping your promises and helping friends keep theirs.',
  'commerce.momentaGuide.streak': 'Keep your streak going',
  'commerce.momentaGuide.streakDetail': 'At {days} days',
  'commerce.momentaGuide.range': '+{min} to {max}',
  'commerce.momentaGuide.review': 'Check a friend’s proof',
  'commerce.momentaGuide.perDay': 'Up to {count} a day',
  'commerce.momentaGuide.invite': 'Invite a friend who joins',
  'commerce.momentaGuide.perYear': 'Up to {count} a year',
  'commerce.momentaGuide.ad': 'Watch a short ad',
  'commerce.momentaGuide.getCta': 'Get Momenta',
  'commerce.momentaGuide.orPro': 'Or go Pro for {amount} every week',
  'commerce.proJourney.yearlyTitle': 'Yearly',
  'commerce.proJourney.weeklyTitle': 'Weekly',
  'commerce.proJourney.yearlyPrice': '{price} a year',
  'commerce.proJourney.thenPerWeek': 'Then {price} a week',
  'commerce.proJourney.renewsWeekly': 'Renews every week',
  'commerce.proJourney.aWeek': 'a week',
  'commerce.proJourney.firstWeekCaption': 'first week',
  'commerce.proJourney.savePercent': 'Save {percent}%',
  'commerce.proJourney.momentaAcrossYear': '{amount} Momenta across the year',
  'commerce.proJourney.momentaEveryWeek': '{amount} Momenta every week',
  'commerce.proJourney.cancelInSettings': 'Cancel anytime in Settings.',
  'commerce.proJourney.continueYearly': 'Continue with yearly',
  'commerce.proJourney.continueWeekly': 'Continue with weekly',
  'commerce.proJourney.restoreShort': 'Restore',
  'commerce.proJourney.planQuestion': 'Same Pro on both. Which suits you?',
  'commerce.proJourney.backToPromise':
    'After you subscribe, I’ll take you straight back to your promise.',
  'commerce.proJourney.backToGroup':
    'After you subscribe, I’ll take you straight back to your group.',
  'commerce.proJourney.momentaRow': 'Momenta',
  'commerce.proJourney.momentaYear': '{amount} across the year',
  'commerce.proJourney.momentaWeek': '{amount} every week',
  'commerce.proJourney.cancelRow': 'Cancel',
  'commerce.proJourney.cancelAnytime': 'Anytime in Settings',
} as const;
