export const todayEnNZ = {
  'today.progress.streak_days': '{count} days',
  'today.progress.streak_days.one': '{count} day',
  'today.progress.streak_days.other': '{count} days',
  'today.progress.day_of': 'Day {day} of {total}',
  'today.progress.day': 'Day {day}',
  'today.progress.current_streak': 'Current streak',
  'today.progress.promise': 'Promise progress',
  'today.progress.accessibility.current_streak': 'Current streak {value}.',
  'today.progress.accessibility.promise': 'Promise progress {value}.',
  'today.all_clear.due_now': 'due now',
  'today.all_clear.accessibility.zero_due': '0 due now.',
  'today.loading.accessibility': 'Loading Today',
  'today.proof.heading': 'Up next',
  'today.proof.solo': 'Solo',
  'today.proof.meta': '{group} · Day {day}/{total} · {status}',
  'today.proof.status.waiting_review': 'Waiting for review',
  'today.proof.status.approved': 'Proof approved',
  'today.proof.status.correction_requested': 'New proof requested',
  'today.proof.status.sent': 'Proof sent',
  'today.proof.status.due_now': 'Proof due now',
  'today.proof.status.due': 'Proof due',
  'today.proof.action.view': 'View',
  'today.proof.action.update': 'Update',
  'today.proof.action.write': 'Write',
  'today.proof.action.record': 'Record',
  'today.proof.action.add_photo': 'Add photo',
  'today.proof.action.add_proof': 'Add proof',
  'today.proof.empty.title': 'No promises yet',
  'today.proof.empty.body':
    'Make a promise and your first check-in will appear here.',
  'today.proof.empty.action': 'Make one',
} as const;
