export const widgetsEnNZ = {
  'widgets.title': 'Home Screen widget',
  'widgets.entryDetail': 'Your streak and next step, at a glance.',
  'widgets.choose': 'Choose your widget',
  'widgets.heading': 'Keep your streak in sight.',
  'widgets.subtitle': 'A little nudge to keep going tomorrow.',
  'widgets.promise': 'Promise',
  'widgets.privatePromise': 'Your promise',
  'widgets.dayStreak': 'day streak',
  'widgets.today': 'Today',
  'widgets.beforeDeadline': 'Before {deadline}',
  'widgets.showText': 'Show promise text',
  'widgets.privateDetail':
    'Your promise text stays inside Menta. Only your streak and progress are shown.',
  'widgets.publicDetail':
    'Visible to anyone who can see your Home Screen. Turn off to show only your progress.',
  'widgets.howToAdd': 'Show me how to add it',
  'widgets.notNow': 'Not now',
  'widgets.instructions': 'See your streak every time you unlock.',
  'widgets.instructionsDetail': 'Add Menta from your device’s widget gallery.',
  'widgets.step1': 'Touch and hold',
  'widgets.step1Detail':
    'Go to your Home Screen. Hold an empty area until the apps jiggle.',
  'widgets.step2': 'Find Menta',
  'widgets.step2Detail':
    'Tap Edit, then Add Widget (or tap +). Search for Menta.',
  'widgets.step3': 'Choose your size',
  'widgets.step3Detail':
    'Choose a size, tap Add Widget, then Done. For the Lock Screen, touch and hold it, choose Customise, then Add Widgets.',
  'widgets.gotIt': 'Got it',
  'widgets.preview': 'Widget preview',
  'widgets.loading': 'Loading your promises',
  'widgets.retry': 'Try again',
  'widgets.error': 'Your widget could not be updated. Try again.',
  'widgets.saveError':
    'Your preference could not be saved. Try again before leaving this screen.',
  'widgets.unavailable':
    'Widgets need the latest iPhone or iPad build of Menta.',
  'widgets.inviteDetail': 'See your streak and next step on your Home Screen.',
  'widgets.seeWidget': 'See the widget',
  'widgets.dismiss': 'Dismiss widget invitation',
  'widgets.history': 'Recent proof',
  'widgets.history.approved': 'Accepted',
  'widgets.history.pending': 'Waiting for review',
  'widgets.history.rejected': 'Needs correction',
  'widgets.state.due.heading': 'Keep it going.',
  'widgets.state.due.detail': 'One more day starts with your next step.',
  'widgets.state.due.action': 'Add today’s proof',
  'widgets.state.risk.heading': 'Still time to keep it.',
  'widgets.state.risk.detail': 'Add proof before {deadline}.',
  'widgets.state.risk.action': 'Add proof now',
  'widgets.state.waiting.heading': 'Proof sent.',
  'widgets.state.waiting.detail': 'Waiting for review.',
  'widgets.state.waiting.action': 'View your proof',
  'widgets.state.accepted.heading': 'You kept it going.',
  'widgets.state.accepted.detail': 'Today’s proof is accepted.',
  'widgets.state.accepted.action': 'See your progress',
  'widgets.state.protected.heading': 'Streak protected.',
  'widgets.state.protected.detail': 'A freeze covered a missed day.',
  'widgets.state.protected.action': 'Add today’s proof',
  'widgets.state.correction.heading': 'A quick fix.',
  'widgets.state.correction.detail': 'Your proof needs a correction.',
  'widgets.state.correction.action': 'Fix your proof',
  'widgets.state.missed.heading': 'Start again today.',
  'widgets.state.missed.detail': 'Your next step still counts.',
  'widgets.state.missed.action': 'Add today’s proof',
  'widgets.state.empty.heading': 'Start with one promise.',
  'widgets.state.empty.detail': 'Choose something you want to do.',
  'widgets.state.empty.action': 'Choose a promise',
  'widgets.state.signed-out.heading': 'Your next promise starts here.',
  'widgets.state.signed-out.detail': 'Sign in to see your streak.',
  'widgets.state.signed-out.action': 'Open Menta',
  'widgets.state.stale.heading': 'Let’s check what’s next.',
  'widgets.state.stale.detail': 'Open Menta for your current streak.',
  'widgets.state.stale.action': 'Open Menta to refresh',
  'widgets.state.choose.heading': 'Give your streak a home.',
  'widgets.state.choose.detail': 'Choose a promise in Menta.',
  'widgets.state.choose.action': 'Choose your promise',
  'widgets.timeLeft.hours': '{hours}h left',
  'widgets.timeLeft.minutes': '{minutes} min left',
  'widgets.status.accepted': 'Done today',
  'widgets.status.waiting': 'Sent · in review',
  'widgets.status.missed': 'Day 1 today',
  'widgets.status.protected': 'Streak protected',
  'widgets.status.correction': 'Needs one fix',
} as const;
