/** Copy for the shared "not enough Momenta" sheet, the Momenta guide and the Pro journey. */
export const momentaTopUpPtPT = {
  'commerce.topUp.toGo': 'Faltam {amount} Momenta',
  'commerce.topUp.getMore': 'Obter mais Momenta',
  'commerce.topUp.inAndToGo': '+{credited} recebidos. Faltam {remaining}.',
  'commerce.topUp.waits.promise':
    'Escolha uma opção. A sua promessa fica à espera aqui.',
  'commerce.topUp.waits.group':
    'Escolha uma opção. O seu grupo fica à espera aqui.',
  'commerce.topUp.waits.join': 'Escolha uma opção. Pode entrar logo a seguir.',
  'commerce.topUp.waits.general': 'Escolha como carregar.',
  'commerce.topUp.oneMoreAd': 'Mais um anúncio e está feito.',
  'commerce.topUp.moreAds': 'Mais {count} anúncios e está feito.',
  'commerce.topUp.adsResting':
    'Não há anúncios de momento. Com o Pro ou uma revisão rápida, consegues.',
  'commerce.topUp.youHave': 'Tens {amount}',
  'commerce.topUp.need.promise': 'Nova promessa · {amount}',
  'commerce.topUp.need.group': 'Novo grupo · {amount}',
  'commerce.topUp.need.join': 'Entrar · {amount}',
  'commerce.topUp.need.general': 'Necessário · {amount}',
  'commerce.topUp.watchTitle': 'Ver um anúncio curto',
  'commerce.topUp.watchAnotherTitle': 'Ver outro',
  'commerce.topUp.watchDetail': 'Cerca de 30 segundos',
  'commerce.topUp.watchCooldown':
    'O próximo fica pronto dentro de alguns minutos',
  'commerce.topUp.watchDailyLimit': 'Por hoje é tudo. Amanhã há mais.',
  'commerce.topUp.proTitle': 'Aderir ao Pro',
  'commerce.topUp.proDetail':
    '{amount} Momenta por semana, sem pausas para anúncios',
  'commerce.topUp.reviewTitle': 'Rever a prova de alguém',
  'commerce.topUp.reviewDetail': '+{amount} por cada prova que reveres',
  'commerce.topUp.watchCta': 'Ver e ganhar {amount}',
  'commerce.topUp.proCta': 'Aderir ao Pro',
  'commerce.topUp.proHint': 'A seguir vês os planos semanal e anual.',
  'commerce.topUp.reviewCta': 'Rever prova',
  'commerce.topUp.whatAre': 'O que são Momenta?',
  'commerce.topUp.notNow': 'Agora não',
  'commerce.topUp.adding': 'A adicionar os seus Momenta',
  'commerce.topUp.addingDetail':
    'Estamos a confirmar o anúncio com a loja. Demora um ou dois segundos.',
  'commerce.topUp.addingCta': 'A adicionar Momenta…',
  'commerce.topUp.safeToClose': 'Pode fechar. Os seus Momenta chegam na mesma.',
  'commerce.topUp.allSet': 'Tudo pronto',
  'commerce.topUp.allSet.promise':
    'Já tem o suficiente para começar a sua promessa.',
  'commerce.topUp.allSet.group': 'Já tem o suficiente para criar o seu grupo.',
  'commerce.topUp.allSet.join': 'Tens o suficiente para entrar.',
  'commerce.topUp.allSet.general': 'Os seus Momenta já estão no seu saldo.',
  'commerce.topUp.fromAds': 'Dos anúncios que viste',
  'commerce.topUp.addedNow': 'Adicionados agora',
  'commerce.topUp.back.promise': 'Voltar à minha promessa',
  'commerce.topUp.back.group': 'Voltar ao meu grupo',
  'commerce.topUp.back.join': 'Voltar para entrar',
  'commerce.topUp.back.general': 'Concluído',
  'commerce.topUp.costs': 'CUSTA',
  'commerce.topUp.leftAfter': 'FICAM DEPOIS',
  'commerce.topUp.youHaveLabel': 'TENS',
  'commerce.topUp.amount': '{amount} Momenta',
  'commerce.topUp.leftOf': '{left} de {balance}',
  'commerce.topUp.getAmountMore': 'Obter mais {amount} Momenta',
  'commerce.topUp.shortBubble':
    'Faltam {amount} Momenta. Eu guardo isto enquanto carregas.',
  'commerce.momentaGuide.close': 'Fechar',
  'commerce.momentaGuide.forTitle': 'Os Momenta dão valor a uma promessa',
  'commerce.momentaGuide.forBody':
    'Começar algo novo custa um pouco, para que cada promessa seja uma que quer mesmo cumprir.',
  'commerce.momentaGuide.promise': 'Começar uma promessa',
  'commerce.momentaGuide.group': 'Criar um grupo',
  'commerce.momentaGuide.join': 'Entrar numa promessa ou grupo',
  'commerce.momentaGuide.firstFree': 'A primeira é grátis',
  'commerce.momentaGuide.firstJoinFree': 'A primeira entrada é grátis',
  'commerce.momentaGuide.free': 'Provas, revisões e sequências',
  'commerce.momentaGuide.alwaysFree': 'Sempre grátis',
  'commerce.momentaGuide.freeValue': 'Grátis',
  'commerce.momentaGuide.howCta': 'Como os obtenho?',
  'commerce.momentaGuide.earnTitle': 'Ganha ao aparecer todos os dias',
  'commerce.momentaGuide.earnBody':
    'A maioria dos Momenta vem de cumprir as suas promessas e de ajudar outras pessoas a cumprir as delas.',
  'commerce.momentaGuide.streak': 'Manter a sua sequência',
  'commerce.momentaGuide.streakDetail': 'Aos {days} dias',
  'commerce.momentaGuide.range': 'De +{min} a {max}',
  'commerce.momentaGuide.review': 'Rever a prova de alguém',
  'commerce.momentaGuide.perDay': 'Até {count} por dia',
  'commerce.momentaGuide.invite': 'Convidar alguém que entre',
  'commerce.momentaGuide.perYear': 'Até {count} por ano',
  'commerce.momentaGuide.ad': 'Ver um anúncio curto',
  'commerce.momentaGuide.getCta': 'Obter Momenta',
  'commerce.momentaGuide.orPro':
    'Ou adere ao Pro por {amount} todas as semanas',
  'commerce.proJourney.planQuestion':
    'O mesmo Pro nos dois. Qual te serve melhor?',
  'commerce.proJourney.backToPromise':
    'Depois de aderir, levo-o diretamente de volta à sua promessa.',
  'commerce.proJourney.backToGroup':
    'Depois de aderir, levo-o diretamente de volta ao seu grupo.',
  'commerce.proJourney.momentaRow': 'Momenta',
  'commerce.proJourney.momentaYear': '{amount} ao longo do ano',
  'commerce.proJourney.momentaWeek': '{amount} todas as semanas',
  'commerce.proJourney.cancelRow': 'Cancelar',
  'commerce.proJourney.cancelAnytime': 'Quando quiser, nas Definições',
} as const;
