/** Copy for the shared "not enough Momenta" sheet, the Momenta guide and the Pro journey. */
export const momentaTopUpPtBR = {
  'commerce.topUp.toGo': 'Faltam {amount} Momenta',
  'commerce.topUp.getMore': 'Conseguir mais Momenta',
  'commerce.topUp.inAndToGo': '+{credited} recebidos. Faltam {remaining}.',
  'commerce.topUp.waits.promise':
    'Escolha uma opção. Sua promessa espera aqui.',
  'commerce.topUp.waits.group': 'Escolha uma opção. Seu grupo espera aqui.',
  'commerce.topUp.waits.join':
    'Escolha uma opção. Você pode entrar logo depois.',
  'commerce.topUp.waits.general': 'Escolha como recarregar.',
  'commerce.topUp.oneMoreAd': 'Mais um anúncio e pronto.',
  'commerce.topUp.moreAds': 'Mais {count} anúncios e pronto.',
  'commerce.topUp.adsResting':
    'Sem anúncios no momento. Com o Pro ou uma revisão rápida, você chega lá.',
  'commerce.topUp.youHave': 'Você tem {amount}',
  'commerce.topUp.need.promise': 'Nova promessa · {amount}',
  'commerce.topUp.need.group': 'Novo grupo · {amount}',
  'commerce.topUp.need.join': 'Entrar · {amount}',
  'commerce.topUp.need.general': 'Necessário · {amount}',
  'commerce.topUp.watchTitle': 'Assistir a um anúncio curto',
  'commerce.topUp.watchAnotherTitle': 'Assistir a outro',
  'commerce.topUp.watchDetail': 'Cerca de 30 segundos',
  'commerce.topUp.watchReadyIn': 'O próximo fica pronto em {time}',
  'commerce.topUp.watchAnotherIn': 'Ver outro em {time}',
  'commerce.topUp.watchCooldown': 'O próximo fica pronto em alguns minutos',
  'commerce.topUp.watchDailyLimit': 'Por hoje é só. Amanhã tem mais.',
  'commerce.topUp.proTitle': 'Assinar o Pro',
  'commerce.topUp.proDetail':
    '{amount} Momenta por semana, sem pausas para anúncios',
  'commerce.topUp.reviewTitle': 'Revisar a prova de alguém',
  'commerce.topUp.reviewDetail': '+{amount} por cada prova que você revisar',
  'commerce.topUp.watchCta': 'Assistir e ganhar {amount}',
  'commerce.topUp.proCta': 'Assinar o Pro',
  'commerce.topUp.proHint': 'Em seguida você vê os planos semanal e anual.',
  'commerce.topUp.reviewCta': 'Revisar prova',
  'commerce.topUp.whatAre': 'O que são Momenta?',
  'commerce.topUp.notNow': 'Agora não',
  'commerce.topUp.adding': 'Adicionando seus Momenta',
  'commerce.topUp.addingDetail':
    'Estamos confirmando o anúncio com a loja. Leva um ou dois segundos.',
  'commerce.topUp.addingCta': 'Adicionando Momenta…',
  'commerce.topUp.safeToClose':
    'Você pode fechar. Seus Momenta chegam mesmo assim.',
  'commerce.topUp.allSet': 'Tudo pronto',
  'commerce.topUp.allSet.promise':
    'Você tem o suficiente para começar sua promessa.',
  'commerce.topUp.allSet.group': 'Você tem o suficiente para criar seu grupo.',
  'commerce.topUp.allSet.join': 'Você tem o suficiente para entrar.',
  'commerce.topUp.allSet.general': 'Seus Momenta já estão no seu saldo.',
  'commerce.topUp.fromAds': 'Dos anúncios que você assistiu',
  'commerce.topUp.addedNow': 'Adicionados agora',
  'commerce.topUp.back.promise': 'Voltar para minha promessa',
  'commerce.topUp.back.group': 'Voltar para meu grupo',
  'commerce.topUp.back.join': 'Voltar para entrar',
  'commerce.topUp.back.general': 'Pronto',
  'commerce.topUp.costs': 'CUSTA',
  'commerce.topUp.leftAfter': 'SOBRA DEPOIS',
  'commerce.topUp.youHaveLabel': 'VOCÊ TEM',
  'commerce.topUp.amount': '{amount} Momenta',
  'commerce.topUp.leftOf': '{left} de {balance}',
  'commerce.topUp.getAmountMore': 'Conseguir mais {amount} Momenta',
  'commerce.topUp.shortBubble':
    'Faltam {amount} Momenta. Eu guardo isto enquanto você recarrega.',
  'commerce.momentaGuide.close': 'Fechar',
  'commerce.momentaGuide.forTitle': 'Momenta fazem uma promessa valer',
  'commerce.momentaGuide.forBody':
    'Começar algo novo custa um pouco, assim cada promessa é uma que você quer mesmo cumprir.',
  'commerce.momentaGuide.promise': 'Começar uma promessa',
  'commerce.momentaGuide.group': 'Criar um grupo',
  'commerce.momentaGuide.join': 'Entrar numa promessa ou grupo',
  'commerce.momentaGuide.firstFree': 'A primeira é grátis',
  'commerce.momentaGuide.firstJoinFree': 'A primeira entrada é grátis',
  'commerce.momentaGuide.free': 'Provas, revisões e sequências',
  'commerce.momentaGuide.alwaysFree': 'Sempre grátis',
  'commerce.momentaGuide.freeValue': 'Grátis',
  'commerce.momentaGuide.howCta': 'Como eu consigo?',
  'commerce.momentaGuide.earnTitle': 'Você ganha aparecendo todo dia',
  'commerce.momentaGuide.earnBody':
    'A maior parte dos Momenta vem de cumprir suas promessas e ajudar outras pessoas a cumprir as delas.',
  'commerce.momentaGuide.streak': 'Manter sua sequência',
  'commerce.momentaGuide.streakDetail': 'Com {days} dias',
  'commerce.momentaGuide.range': 'De +{min} a {max}',
  'commerce.momentaGuide.review': 'Revisar a prova de alguém',
  'commerce.momentaGuide.perDay': 'Até {count} por dia',
  'commerce.momentaGuide.invite': 'Convidar alguém que entrar',
  'commerce.momentaGuide.perYear': 'Até {count} por ano',
  'commerce.momentaGuide.ad': 'Assistir a um anúncio curto',
  'commerce.momentaGuide.getCta': 'Conseguir Momenta',
  'commerce.momentaGuide.orPro': 'Ou assine o Pro por {amount} toda semana',
  'commerce.proJourney.yearlyTitle': 'Anual',
  'commerce.proJourney.weeklyTitle': 'Semanal',
  'commerce.proJourney.yearlyPrice': '{price} por ano',
  'commerce.proJourney.thenPerWeek': 'Depois, {price} por semana',
  'commerce.proJourney.renewsWeekly': 'Renova toda semana',
  'commerce.proJourney.aWeek': 'por semana',
  'commerce.proJourney.firstWeekCaption': 'primeira semana',
  'commerce.proJourney.savePercent': 'Economize {percent}%',
  'commerce.proJourney.momentaAcrossYear': '{amount} Momenta ao longo do ano',
  'commerce.proJourney.momentaEveryWeek': '{amount} Momenta toda semana',
  'commerce.proJourney.cancelInSettings': 'Cancele quando quiser em Ajustes.',
  'commerce.proJourney.continueYearly': 'Continuar com o anual',
  'commerce.proJourney.continueWeekly': 'Continuar com o semanal',
  'commerce.proJourney.restoreShort': 'Restaurar',
  'commerce.proJourney.planQuestion':
    'O mesmo Pro nos dois. Qual combina com você?',
  'commerce.proJourney.backToPromise':
    'Depois de assinar, eu te levo direto de volta para sua promessa.',
  'commerce.proJourney.backToGroup':
    'Depois de assinar, eu te levo direto de volta para seu grupo.',
  'commerce.proJourney.momentaRow': 'Momenta',
  'commerce.proJourney.momentaYear': '{amount} ao longo do ano',
  'commerce.proJourney.momentaWeek': '{amount} toda semana',
  'commerce.proJourney.cancelRow': 'Cancelar',
  'commerce.proJourney.cancelAnytime': 'Quando quiser em Ajustes',
} as const;
