/** Copy for the shared "not enough Momenta" sheet, the Momenta guide and the Pro journey. */
export const momentaTopUpEsES = {
  'commerce.topUp.toGo': 'Faltan {amount} Momenta',
  'commerce.topUp.getMore': 'Consigue más Momenta',
  'commerce.topUp.inAndToGo': '+{credited} dentro. Faltan {remaining}.',
  'commerce.topUp.waits.promise':
    'Elige una opción. Tu promesa te espera aquí.',
  'commerce.topUp.waits.group': 'Elige una opción. Tu grupo te espera aquí.',
  'commerce.topUp.waits.join': 'Elige una opción. Podrás unirte justo después.',
  'commerce.topUp.waits.general': 'Elige cómo recargar.',
  'commerce.topUp.oneMoreAd': 'Un anuncio más y lo tienes.',
  'commerce.topUp.moreAds': '{count} anuncios más y lo tienes.',
  'commerce.topUp.adsResting':
    'Ahora mismo no hay anuncios. Con Pro o una revisión rápida lo consigues.',
  'commerce.topUp.youHave': 'Tienes {amount}',
  'commerce.topUp.need.promise': 'Nueva promesa · {amount}',
  'commerce.topUp.need.group': 'Nuevo grupo · {amount}',
  'commerce.topUp.need.join': 'Unirte · {amount}',
  'commerce.topUp.need.general': 'Necesitas · {amount}',
  'commerce.topUp.watchTitle': 'Ver un anuncio corto',
  'commerce.topUp.watchAnotherTitle': 'Ver otro',
  'commerce.topUp.watchDetail': 'Unos 30 segundos',
  'commerce.topUp.watchReadyIn': 'El siguiente estará listo en {time}',
  'commerce.topUp.watchAnotherIn': 'Ver otro en {time}',
  'commerce.topUp.watchCooldown':
    'El siguiente estará listo en un par de minutos',
  'commerce.topUp.watchDailyLimit': 'Eso es todo por hoy. Mañana hay más.',
  'commerce.topUp.proTitle': 'Hazte Pro',
  'commerce.topUp.proDetail':
    '{amount} Momenta a la semana, sin pausas publicitarias',
  'commerce.topUp.reviewTitle': 'Revisa la prueba de alguien',
  'commerce.topUp.reviewDetail': '+{amount} por cada prueba que revises',
  'commerce.topUp.watchCta': 'Ver y conseguir {amount}',
  'commerce.topUp.proCta': 'Hazte Pro',
  'commerce.topUp.proHint': 'A continuación verás los planes semanal y anual.',
  'commerce.topUp.reviewCta': 'Revisar prueba',
  'commerce.topUp.whatAre': '¿Qué son los Momenta?',
  'commerce.topUp.notNow': 'Ahora no',
  'commerce.topUp.adding': 'Añadiendo tus Momenta',
  'commerce.topUp.addingDetail':
    'Estamos comprobando el anuncio con la tienda. Suele tardar un segundo o dos.',
  'commerce.topUp.addingCta': 'Añadiendo Momenta…',
  'commerce.topUp.safeToClose':
    'Puedes cerrar esto. Tus Momenta llegarán igual.',
  'commerce.topUp.allSet': 'Todo listo',
  'commerce.topUp.allSet.promise': 'Tienes suficiente para empezar tu promesa.',
  'commerce.topUp.allSet.group': 'Tienes suficiente para empezar tu grupo.',
  'commerce.topUp.allSet.join': 'Tienes suficiente para unirte.',
  'commerce.topUp.allSet.general': 'Tus Momenta ya están en tu saldo.',
  'commerce.topUp.fromAds': 'De los anuncios que viste',
  'commerce.topUp.addedNow': 'Añadidos ahora mismo',
  'commerce.topUp.back.promise': 'Volver a mi promesa',
  'commerce.topUp.back.group': 'Volver a mi grupo',
  'commerce.topUp.back.join': 'Volver a unirme',
  'commerce.topUp.back.general': 'Hecho',
  'commerce.topUp.costs': 'CUESTA',
  'commerce.topUp.leftAfter': 'TE QUEDARÁN',
  'commerce.topUp.youHaveLabel': 'TIENES',
  'commerce.topUp.amount': '{amount} Momenta',
  'commerce.topUp.leftOf': '{left} de {balance}',
  'commerce.topUp.getAmountMore': 'Consigue {amount} Momenta más',
  'commerce.topUp.shortBubble':
    'Nos faltan {amount} Momenta. Guardo esto mientras recargas.',
  'commerce.momentaGuide.close': 'Cerrar',
  'commerce.momentaGuide.forTitle': 'Los Momenta hacen que una promesa cuente',
  'commerce.momentaGuide.forBody':
    'Empezar algo nuevo cuesta un poco, así cada promesa es una que de verdad quieres cumplir.',
  'commerce.momentaGuide.promise': 'Empezar una promesa',
  'commerce.momentaGuide.group': 'Empezar un grupo',
  'commerce.momentaGuide.join': 'Unirte a una promesa o grupo',
  'commerce.momentaGuide.firstFree': 'La primera es gratis',
  'commerce.momentaGuide.firstJoinFree': 'La primera vez que te unes es gratis',
  'commerce.momentaGuide.free': 'Pruebas, revisiones y rachas',
  'commerce.momentaGuide.alwaysFree': 'Siempre gratis',
  'commerce.momentaGuide.freeValue': 'Gratis',
  'commerce.momentaGuide.howCta': '¿Cómo los consigo?',
  'commerce.momentaGuide.earnTitle': 'Los ganas apareciendo cada día',
  'commerce.momentaGuide.earnBody':
    'La mayoría de los Momenta llegan al cumplir tus promesas y ayudar a otros a cumplir las suyas.',
  'commerce.momentaGuide.streak': 'Mantén tu racha',
  'commerce.momentaGuide.streakDetail': 'A los {days} días',
  'commerce.momentaGuide.range': 'De +{min} a {max}',
  'commerce.momentaGuide.review': 'Revisa la prueba de alguien',
  'commerce.momentaGuide.perDay': 'Hasta {count} al día',
  'commerce.momentaGuide.invite': 'Invita a alguien que se una',
  'commerce.momentaGuide.perYear': 'Hasta {count} al año',
  'commerce.momentaGuide.ad': 'Ver un anuncio corto',
  'commerce.momentaGuide.getCta': 'Conseguir Momenta',
  'commerce.momentaGuide.orPro': 'O hazte Pro por {amount} cada semana',
  'commerce.proJourney.yearlyTitle': 'Anual',
  'commerce.proJourney.weeklyTitle': 'Semanal',
  'commerce.proJourney.yearlyPrice': '{price} al año',
  'commerce.proJourney.thenPerWeek': 'Después, {price} a la semana',
  'commerce.proJourney.renewsWeekly': 'Se renueva cada semana',
  'commerce.proJourney.aWeek': 'a la semana',
  'commerce.proJourney.firstWeekCaption': 'primera semana',
  'commerce.proJourney.savePercent': 'Ahorra un {percent} %',
  'commerce.proJourney.momentaAcrossYear': '{amount} Momenta durante el año',
  'commerce.proJourney.momentaEveryWeek': '{amount} Momenta cada semana',
  'commerce.proJourney.cancelInSettings': 'Cancela cuando quieras en Ajustes.',
  'commerce.proJourney.continueYearly': 'Continuar con el anual',
  'commerce.proJourney.continueWeekly': 'Continuar con el semanal',
  'commerce.proJourney.restoreShort': 'Restaurar',
  'commerce.proJourney.planQuestion':
    'Es el mismo Pro en los dos. ¿Cuál te va mejor?',
  'commerce.proJourney.backToPromise':
    'Cuando te suscribas, te llevo directo de vuelta a tu promesa.',
  'commerce.proJourney.backToGroup':
    'Cuando te suscribas, te llevo directo de vuelta a tu grupo.',
  'commerce.proJourney.momentaRow': 'Momenta',
  'commerce.proJourney.momentaYear': '{amount} a lo largo del año',
  'commerce.proJourney.momentaWeek': '{amount} cada semana',
  'commerce.proJourney.cancelRow': 'Cancelar',
  'commerce.proJourney.cancelAnytime': 'Cuando quieras en Ajustes',
} as const;
