/** Copy for the shared "not enough Momenta" sheet, the Momenta guide and the Pro journey. */
export const momentaTopUpDeDE = {
  'commerce.topUp.toGo': 'Noch {amount} Momenta',
  'commerce.topUp.getMore': 'Mehr Momenta holen',
  'commerce.topUp.inAndToGo': '+{credited} da. Noch {remaining}.',
  'commerce.topUp.waits.promise':
    'Wähle einen Weg. Dein Versprechen wartet hier.',
  'commerce.topUp.waits.group': 'Wähle einen Weg. Deine Gruppe wartet hier.',
  'commerce.topUp.waits.join':
    'Wähle einen Weg. Danach kannst du direkt beitreten.',
  'commerce.topUp.waits.general': 'Wähle einen Weg zum Aufladen.',
  'commerce.topUp.oneMoreAd': 'Noch eine Werbung, dann hast du es.',
  'commerce.topUp.moreAds': 'Noch {count} Werbungen, dann hast du es.',
  'commerce.topUp.adsResting':
    'Gerade gibt es keine Werbung. Mit Pro oder einer kurzen Prüfung klappt es trotzdem.',
  'commerce.topUp.youHave': 'Du hast {amount}',
  'commerce.topUp.need.promise': 'Neues Versprechen · {amount}',
  'commerce.topUp.need.group': 'Neue Gruppe · {amount}',
  'commerce.topUp.need.join': 'Beitreten · {amount}',
  'commerce.topUp.need.general': 'Benötigt · {amount}',
  'commerce.topUp.watchTitle': 'Kurze Werbung ansehen',
  'commerce.topUp.watchAnotherTitle': 'Noch eine ansehen',
  'commerce.topUp.watchDetail': 'Etwa 30 Sekunden',
  'commerce.topUp.watchCooldown': 'Die nächste ist in ein paar Minuten bereit',
  'commerce.topUp.watchDailyLimit': 'Das war’s für heute. Morgen gibt es mehr.',
  'commerce.topUp.proTitle': 'Pro holen',
  'commerce.topUp.proDetail': '{amount} Momenta pro Woche, keine Werbepausen',
  'commerce.topUp.reviewTitle': 'Nachweis von Freund:innen prüfen',
  'commerce.topUp.reviewDetail': '+{amount} für jeden geprüften Nachweis',
  'commerce.topUp.watchCta': 'Ansehen und {amount} bekommen',
  'commerce.topUp.proCta': 'Pro holen',
  'commerce.topUp.proHint': 'Als Nächstes siehst du Wochen- und Jahrespläne.',
  'commerce.topUp.reviewCta': 'Nachweis prüfen',
  'commerce.topUp.whatAre': 'Was sind Momenta?',
  'commerce.topUp.notNow': 'Nicht jetzt',
  'commerce.topUp.adding': 'Deine Momenta kommen',
  'commerce.topUp.addingDetail':
    'Wir prüfen die Werbung beim Store. Das dauert meist ein, zwei Sekunden.',
  'commerce.topUp.addingCta': 'Momenta werden gutgeschrieben…',
  'commerce.topUp.safeToClose':
    'Du kannst das schließen. Deine Momenta kommen trotzdem an.',
  'commerce.topUp.allSet': 'Alles bereit',
  'commerce.topUp.allSet.promise':
    'Du hast genug, um dein Versprechen zu starten.',
  'commerce.topUp.allSet.group': 'Du hast genug, um deine Gruppe zu starten.',
  'commerce.topUp.allSet.join': 'Du hast genug, um beizutreten.',
  'commerce.topUp.allSet.general': 'Deine Momenta sind auf deinem Konto.',
  'commerce.topUp.fromAds': 'Aus angesehener Werbung',
  'commerce.topUp.addedNow': 'Gerade gutgeschrieben',
  'commerce.topUp.back.promise': 'Zurück zu meinem Versprechen',
  'commerce.topUp.back.group': 'Zurück zu meiner Gruppe',
  'commerce.topUp.back.join': 'Zurück zum Beitreten',
  'commerce.topUp.back.general': 'Fertig',
  'commerce.topUp.costs': 'KOSTET',
  'commerce.topUp.leftAfter': 'DANACH ÜBRIG',
  'commerce.topUp.youHaveLabel': 'DU HAST',
  'commerce.topUp.amount': '{amount} Momenta',
  'commerce.topUp.leftOf': '{left} von {balance}',
  'commerce.topUp.getAmountMore': '{amount} Momenta mehr holen',
  'commerce.topUp.shortBubble':
    'Uns fehlen {amount} Momenta. Ich halte das hier fest, während du auflädst.',
  'commerce.momentaGuide.close': 'Schließen',
  'commerce.momentaGuide.forTitle': 'Momenta geben einem Versprechen Gewicht',
  'commerce.momentaGuide.forBody':
    'Etwas Neues zu starten kostet ein wenig, damit jedes Versprechen ernst gemeint ist.',
  'commerce.momentaGuide.promise': 'Versprechen starten',
  'commerce.momentaGuide.group': 'Gruppe starten',
  'commerce.momentaGuide.join': 'Einem Versprechen oder einer Gruppe beitreten',
  'commerce.momentaGuide.firstFree': 'Das erste ist kostenlos',
  'commerce.momentaGuide.firstJoinFree': 'Der erste Beitritt ist kostenlos',
  'commerce.momentaGuide.free': 'Nachweise, Prüfungen und Serien',
  'commerce.momentaGuide.alwaysFree': 'Immer kostenlos',
  'commerce.momentaGuide.freeValue': 'Kostenlos',
  'commerce.momentaGuide.howCta': 'Wie bekomme ich sie?',
  'commerce.momentaGuide.earnTitle': 'Du verdienst sie, indem du dranbleibst',
  'commerce.momentaGuide.earnBody':
    'Die meisten Momenta bekommst du, wenn du deine Versprechen hältst und anderen hilfst, ihre zu halten.',
  'commerce.momentaGuide.streak': 'Deine Serie halten',
  'commerce.momentaGuide.streakDetail': 'Nach {days} Tagen',
  'commerce.momentaGuide.range': '+{min} bis {max}',
  'commerce.momentaGuide.review': 'Nachweis von Freund:innen prüfen',
  'commerce.momentaGuide.perDay': 'Bis zu {count} am Tag',
  'commerce.momentaGuide.invite': 'Jemanden einladen, der mitmacht',
  'commerce.momentaGuide.perYear': 'Bis zu {count} im Jahr',
  'commerce.momentaGuide.ad': 'Kurze Werbung ansehen',
  'commerce.momentaGuide.getCta': 'Momenta holen',
  'commerce.momentaGuide.orPro': 'Oder hol dir Pro für {amount} pro Woche',
  'commerce.proJourney.planQuestion':
    'Beide sind dasselbe Pro. Was passt zu dir?',
  'commerce.proJourney.backToPromise':
    'Nach dem Abo bringe ich dich direkt zurück zu deinem Versprechen.',
  'commerce.proJourney.backToGroup':
    'Nach dem Abo bringe ich dich direkt zurück zu deiner Gruppe.',
  'commerce.proJourney.momentaRow': 'Momenta',
  'commerce.proJourney.momentaYear': '{amount} übers Jahr',
  'commerce.proJourney.momentaWeek': '{amount} pro Woche',
  'commerce.proJourney.cancelRow': 'Kündigen',
  'commerce.proJourney.cancelAnytime': 'Jederzeit in den Einstellungen',
} as const;
