import type { widgetsEnNZ } from '../en-NZ/widgets';

export const widgetsdeDE = {
  'widgets.title': 'Widget für den Home-Bildschirm',
  'widgets.entryDetail':
    'Deine Serie und dein nächster Schritt auf einen Blick.',
  'widgets.choose': 'Widget auswählen',
  'widgets.heading': 'Behalte deine Serie im Blick.',
  'widgets.subtitle': 'Ein kleiner Anstoß, morgen weiterzumachen.',
  'widgets.promise': 'Versprechen',
  'widgets.privatePromise': 'Dein Versprechen',
  'widgets.dayStreak': 'Tage in Folge',
  'widgets.today': 'Heute',
  'widgets.beforeDeadline': 'Vor {deadline}',
  'widgets.showText': 'Versprechen anzeigen',
  'widgets.privateDetail':
    'Dein Versprechen bleibt in Menta. Angezeigt werden nur deine Serie und dein Fortschritt.',
  'widgets.publicDetail':
    'Für alle sichtbar, die deinen Home-Bildschirm sehen können. Deaktiviere dies, um nur deinen Fortschritt anzuzeigen.',
  'widgets.howToAdd': 'So fügst du es hinzu',
  'widgets.notNow': 'Nicht jetzt',
  'widgets.instructions': 'Sieh deine Serie bei jedem Entsperren.',
  'widgets.instructionsDetail':
    'Füge Menta über die Widget-Galerie deines Geräts hinzu.',
  'widgets.step1': 'Gedrückt halten',
  'widgets.step1Detail':
    'Halte eine leere Stelle auf dem Home-Bildschirm gedrückt, bis die Apps wackeln.',
  'widgets.step2': 'Menta finden',
  'widgets.step2Detail':
    'Tippe auf Bearbeiten und dann auf Widget hinzufügen (oder auf +). Suche nach Menta.',
  'widgets.step3': 'Größe auswählen',
  'widgets.step3Detail':
    'Wähle eine Größe, tippe auf Widget hinzufügen und dann auf Fertig. Für den Sperrbildschirm: gedrückt halten, Anpassen und Widgets hinzufügen wählen.',
  'widgets.gotIt': 'Verstanden',
  'widgets.preview': 'Widget-Vorschau',
  'widgets.loading': 'Deine Versprechen werden geladen',
  'widgets.retry': 'Erneut versuchen',
  'widgets.error':
    'Dein Widget konnte nicht aktualisiert werden. Versuche es erneut.',
  'widgets.saveError':
    'Deine Einstellung konnte nicht gespeichert werden. Versuche es erneut, bevor du diese Ansicht verlässt.',
  'widgets.unavailable':
    'Widgets benötigen die neueste iPhone- oder iPad-Version von Menta.',
  'widgets.inviteDetail':
    'Sieh deine Serie und deinen nächsten Schritt auf dem Home-Bildschirm.',
  'widgets.seeWidget': 'Widget ansehen',
  'widgets.dismiss': 'Widget-Hinweis schließen',
  'widgets.history': 'Letzte Nachweise',
  'widgets.history.approved': 'Akzeptiert',
  'widgets.history.pending': 'Wartet auf Prüfung',
  'widgets.history.rejected': 'Korrektur erforderlich',
  'widgets.state.due.heading': 'Bleib dran.',
  'widgets.state.due.detail':
    'Ein weiterer Tag beginnt mit deinem nächsten Schritt.',
  'widgets.state.due.action': 'Heutigen Nachweis hinzufügen',
  'widgets.state.risk.heading': 'Du kannst es noch schaffen.',
  'widgets.state.risk.detail': 'Füge deinen Nachweis vor {deadline} hinzu.',
  'widgets.state.risk.action': 'Nachweis jetzt hinzufügen',
  'widgets.state.waiting.heading': 'Nachweis gesendet.',
  'widgets.state.waiting.detail': 'Wartet auf Prüfung.',
  'widgets.state.waiting.action': 'Deinen Nachweis ansehen',
  'widgets.state.accepted.heading': 'Du bist drangeblieben.',
  'widgets.state.accepted.detail': 'Der heutige Nachweis wurde akzeptiert.',
  'widgets.state.accepted.action': 'Fortschritt ansehen',
  'widgets.state.protected.heading': 'Serie geschützt.',
  'widgets.state.protected.detail':
    'Ein Schutz hat einen verpassten Tag ausgeglichen.',
  'widgets.state.protected.action': 'Heutigen Nachweis hinzufügen',
  'widgets.state.correction.heading': 'Eine kleine Korrektur.',
  'widgets.state.correction.detail': 'Dein Nachweis muss korrigiert werden.',
  'widgets.state.correction.action': 'Nachweis korrigieren',
  'widgets.state.missed.heading': 'Heute neu beginnen.',
  'widgets.state.missed.detail': 'Dein nächster Schritt zählt weiterhin.',
  'widgets.state.missed.action': 'Heutigen Nachweis hinzufügen',
  'widgets.state.empty.heading': 'Beginne mit einem Versprechen.',
  'widgets.state.empty.detail': 'Wähle etwas, das du tun möchtest.',
  'widgets.state.empty.action': 'Versprechen auswählen',
  'widgets.state.signed-out.heading': 'Dein nächstes Versprechen beginnt hier.',
  'widgets.state.signed-out.detail': 'Melde dich an, um deine Serie zu sehen.',
  'widgets.state.signed-out.action': 'Menta öffnen',
  'widgets.state.stale.heading': 'Schauen wir, was als Nächstes ansteht.',
  'widgets.state.stale.detail': 'Öffne Menta für deine aktuelle Serie.',
  'widgets.state.stale.action': 'Zum Aktualisieren Menta öffnen',
  'widgets.state.choose.heading': 'Gib deiner Serie einen Platz.',
  'widgets.state.choose.detail': 'Wähle ein Versprechen in Menta.',
  'widgets.state.choose.action': 'Dein Versprechen auswählen',
  'widgets.timeLeft.hours': 'noch {hours} Std.',
  'widgets.timeLeft.minutes': 'noch {minutes} Min.',
  'widgets.status.accepted': 'Heute erledigt',
  'widgets.status.waiting': 'Gesendet · in Prüfung',
  'widgets.status.missed': 'Heute ist Tag 1',
  'widgets.status.protected': 'Serie geschützt',
  'widgets.status.correction': 'Braucht eine Korrektur',
} as const satisfies Record<keyof typeof widgetsEnNZ, string>;
