import type { widgetsEnNZ } from '../en-NZ/widgets';

export const widgetsptPT = {
  'widgets.title': 'Widget do ecrã principal',
  'widgets.entryDetail': 'A tua sequência e o próximo passo, num relance.',
  'widgets.choose': 'Escolher o widget',
  'widgets.heading': 'Mantém a tua sequência à vista.',
  'widgets.subtitle': 'Um pequeno lembrete para continuares amanhã.',
  'widgets.promise': 'Promessa',
  'widgets.privatePromise': 'A tua promessa',
  'widgets.dayStreak': 'dias seguidos',
  'widgets.today': 'Hoje',
  'widgets.beforeDeadline': 'Antes de {deadline}',
  'widgets.showText': 'Mostrar o texto da promessa',
  'widgets.privateDetail':
    'O texto da tua promessa fica no Menta. Só são mostrados a tua sequência e o teu progresso.',
  'widgets.publicDetail':
    'Visível para quem conseguir ver o teu ecrã principal. Desativa para mostrar apenas o teu progresso.',
  'widgets.howToAdd': 'Como adicionar',
  'widgets.notNow': 'Agora não',
  'widgets.instructions': 'Vê a tua sequência sempre que desbloqueias.',
  'widgets.instructionsDetail':
    'Adiciona o Menta a partir da galeria de widgets do dispositivo.',
  'widgets.step1': 'Toca sem largar',
  'widgets.step1Detail':
    'No ecrã principal, toca sem largar numa área vazia até as apps começarem a abanar.',
  'widgets.step2': 'Encontra o Menta',
  'widgets.step2Detail':
    'Toca em Editar e depois em Adicionar widget (ou em +). Procura Menta.',
  'widgets.step3': 'Escolhe o tamanho',
  'widgets.step3Detail':
    'Escolhe um tamanho, toca em Adicionar widget e depois em OK. No ecrã bloqueado, toca sem largar, escolhe Personalizar e depois Adicionar widgets.',
  'widgets.gotIt': 'Percebi',
  'widgets.preview': 'Pré-visualização do widget',
  'widgets.loading': 'A carregar as tuas promessas',
  'widgets.retry': 'Tentar novamente',
  'widgets.error': 'Não foi possível atualizar o teu widget. Tenta novamente.',
  'widgets.saveError':
    'Não foi possível guardar a tua preferência. Tenta novamente antes de saíres deste ecrã.',
  'widgets.unavailable':
    'Os widgets precisam da versão mais recente do Menta para iPhone ou iPad.',
  'widgets.inviteDetail':
    'Vê a tua sequência e o próximo passo no ecrã principal.',
  'widgets.seeWidget': 'Ver o widget',
  'widgets.dismiss': 'Dispensar sugestão de widget',
  'widgets.history': 'Provas recentes',
  'widgets.history.approved': 'Aceite',
  'widgets.history.pending': 'A aguardar revisão',
  'widgets.history.rejected': 'Precisa de correção',
  'widgets.state.due.heading': 'Continua assim.',
  'widgets.state.due.detail':
    'Hoje ainda precisa de comprovativo antes de {deadline}.',
  'widgets.state.due.action': 'Adicionar a prova de hoje',
  'widgets.state.risk.heading': 'Ainda vais a tempo.',
  'widgets.state.risk.detail': 'Adiciona a tua prova antes de {deadline}.',
  'widgets.state.risk.action': 'Adicionar prova agora',
  'widgets.state.waiting.heading': 'Prova enviada.',
  'widgets.state.waiting.detail':
    'Hoje ainda não conta. Alguém ainda precisa de aceitar o comprovativo.',
  'widgets.state.waiting.action': 'Ver a tua prova',
  'widgets.state.accepted.heading': 'Continuaste.',
  'widgets.state.accepted.detail': 'A prova de hoje foi aceite.',
  'widgets.state.accepted.action': 'Ver o teu progresso',
  'widgets.state.protected.heading': 'Sequência protegida.',
  'widgets.state.protected.detail':
    'Uma proteção de sequência cobriu um dia falhado.',
  'widgets.state.protected.action': 'Adicionar a prova de hoje',
  'widgets.state.correction.heading': 'Uma pequena correção.',
  'widgets.state.correction.detail': 'A tua prova precisa de uma correção.',
  'widgets.state.correction.action': 'Corrigir a tua prova',
  'widgets.state.missed.heading': 'Recomeça hoje.',
  'widgets.state.missed.detail': 'O teu próximo passo continua a contar.',
  'widgets.state.missed.action': 'Adicionar a prova de hoje',
  'widgets.state.empty.heading': 'Começa com uma promessa.',
  'widgets.state.empty.detail': 'Escolhe algo que queiras fazer.',
  'widgets.state.empty.action': 'Escolher uma promessa',
  'widgets.state.signed-out.heading': 'A tua próxima promessa começa aqui.',
  'widgets.state.signed-out.detail':
    'Inicia sessão para veres a tua sequência.',
  'widgets.state.signed-out.action': 'Abrir Menta',
  'widgets.state.stale.heading': 'Vamos ver o próximo passo.',
  'widgets.state.stale.detail':
    'Abre o Menta para veres a tua sequência atual.',
  'widgets.state.stale.action': 'Abrir Menta para atualizar',
  'widgets.state.choose.heading': 'Dá um lugar à tua sequência.',
  'widgets.state.choose.detail': 'Escolhe uma promessa no Menta.',
  'widgets.state.choose.action': 'Escolher a tua promessa',
  'widgets.timeLeft.hours': 'faltam {hours}h',
  'widgets.timeLeft.minutes': 'faltam {minutes} min',
  'widgets.status.accepted': 'Feito hoje',
  'widgets.status.waiting': 'Enviada · em análise',
  'widgets.status.missed': 'Hoje é o dia 1',
  'widgets.status.protected': 'Sequência protegida',
  'widgets.status.correction': 'Precisa de um ajuste',
} as const satisfies Record<keyof typeof widgetsEnNZ, string>;
