import type { widgetsEnNZ } from '../en-NZ/widgets';

export const widgetsptBR = {
  'widgets.title': 'Widget da tela inicial',
  'widgets.entryDetail': 'Sua sequência e seu próximo passo em um só olhar.',
  'widgets.choose': 'Escolher seu widget',
  'widgets.heading': 'Mantenha sua sequência à vista.',
  'widgets.subtitle': 'Um pequeno lembrete para continuar amanhã.',
  'widgets.promise': 'Promessa',
  'widgets.privatePromise': 'Sua promessa',
  'widgets.dayStreak': 'dias seguidos',
  'widgets.today': 'Hoje',
  'widgets.beforeDeadline': 'Antes de {deadline}',
  'widgets.showText': 'Mostrar o texto da promessa',
  'widgets.privateDetail':
    'O texto da sua promessa fica no Menta. Só sua sequência e seu progresso são mostrados.',
  'widgets.publicDetail':
    'Visível para quem puder ver sua tela inicial. Desative para mostrar apenas seu progresso.',
  'widgets.howToAdd': 'Como adicionar',
  'widgets.notNow': 'Agora não',
  'widgets.instructions': 'Veja sua sequência sempre que desbloquear.',
  'widgets.instructionsDetail':
    'Adicione o Menta pela galeria de widgets do seu dispositivo.',
  'widgets.step1': 'Toque e segure',
  'widgets.step1Detail':
    'Na tela inicial, toque e segure uma área vazia até os apps começarem a tremer.',
  'widgets.step2': 'Encontre o Menta',
  'widgets.step2Detail':
    'Toque em Editar e depois em Adicionar Widget (ou em +). Busque Menta.',
  'widgets.step3': 'Escolha o tamanho',
  'widgets.step3Detail':
    'Escolha um tamanho, toque em Adicionar Widget e depois em OK. Na tela bloqueada, toque e segure, escolha Personalizar e depois Adicionar Widgets.',
  'widgets.gotIt': 'Entendi',
  'widgets.preview': 'Prévia do widget',
  'widgets.loading': 'Carregando suas promessas',
  'widgets.retry': 'Tentar novamente',
  'widgets.error': 'Não foi possível atualizar seu widget. Tente novamente.',
  'widgets.saveError':
    'Não foi possível salvar sua preferência. Tente novamente antes de sair desta tela.',
  'widgets.unavailable':
    'Os widgets precisam da versão mais recente do Menta para iPhone ou iPad.',
  'widgets.inviteDetail':
    'Veja sua sequência e seu próximo passo na tela inicial.',
  'widgets.seeWidget': 'Ver o widget',
  'widgets.dismiss': 'Dispensar sugestão de widget',
  'widgets.history': 'Provas recentes',
  'widgets.history.approved': 'Aceita',
  'widgets.history.pending': 'Aguardando análise',
  'widgets.history.rejected': 'Precisa de correção',
  'widgets.state.due.heading': 'Continue assim.',
  'widgets.state.due.detail':
    'Hoje ainda precisa de comprovação antes de {deadline}.',
  'widgets.state.due.action': 'Adicionar a prova de hoje',
  'widgets.state.risk.heading': 'Ainda dá tempo.',
  'widgets.state.risk.detail': 'Adicione sua prova antes de {deadline}.',
  'widgets.state.risk.action': 'Adicionar prova agora',
  'widgets.state.waiting.heading': 'Prova enviada.',
  'widgets.state.waiting.detail':
    'Hoje ainda não conta. Alguém ainda precisa aceitar a comprovação.',
  'widgets.state.waiting.action': 'Ver sua prova',
  'widgets.state.accepted.heading': 'Você continuou.',
  'widgets.state.accepted.detail': 'A prova de hoje foi aceita.',
  'widgets.state.accepted.action': 'Ver seu progresso',
  'widgets.state.protected.heading': 'Sequência protegida.',
  'widgets.state.protected.detail':
    'Uma proteção de sequência cobriu um dia perdido.',
  'widgets.state.protected.action': 'Adicionar a prova de hoje',
  'widgets.state.correction.heading': 'Uma pequena correção.',
  'widgets.state.correction.detail': 'Sua prova precisa de uma correção.',
  'widgets.state.correction.action': 'Corrigir sua prova',
  'widgets.state.missed.heading': 'Recomece hoje.',
  'widgets.state.missed.detail': 'Seu próximo passo continua contando.',
  'widgets.state.missed.action': 'Adicionar a prova de hoje',
  'widgets.state.empty.heading': 'Comece com uma promessa.',
  'widgets.state.empty.detail': 'Escolha algo que você quer fazer.',
  'widgets.state.empty.action': 'Escolher uma promessa',
  'widgets.state.signed-out.heading': 'Sua próxima promessa começa aqui.',
  'widgets.state.signed-out.detail': 'Entre para ver sua sequência.',
  'widgets.state.signed-out.action': 'Abrir Menta',
  'widgets.state.stale.heading': 'Vamos ver o próximo passo.',
  'widgets.state.stale.detail': 'Abra o Menta para ver sua sequência atual.',
  'widgets.state.stale.action': 'Abrir Menta para atualizar',
  'widgets.state.choose.heading': 'Dê um lugar à sua sequência.',
  'widgets.state.choose.detail': 'Escolha uma promessa no Menta.',
  'widgets.state.choose.action': 'Escolher sua promessa',
  'widgets.timeLeft.hours': 'faltam {hours}h',
  'widgets.timeLeft.minutes': 'faltam {minutes} min',
  'widgets.status.accepted': 'Feito hoje',
  'widgets.status.waiting': 'Enviada · em análise',
  'widgets.status.missed': 'Hoje é o dia 1',
  'widgets.status.protected': 'Sequência protegida',
  'widgets.status.correction': 'Precisa de um ajuste',
} as const satisfies Record<keyof typeof widgetsEnNZ, string>;
