import type { widgetsEnNZ } from '../en-NZ/widgets';

export const widgetses = {
  'widgets.title': 'Widget de pantalla de inicio',
  'widgets.entryDetail': 'Tu racha y tu próximo paso, de un vistazo.',
  'widgets.choose': 'Elige tu widget',
  'widgets.heading': 'Mantén tu racha a la vista.',
  'widgets.subtitle': 'Un pequeño recordatorio para seguir mañana.',
  'widgets.promise': 'Promesa',
  'widgets.privatePromise': 'Tu promesa',
  'widgets.dayStreak': 'días seguidos',
  'widgets.today': 'Hoy',
  'widgets.beforeDeadline': 'Antes de {deadline}',
  'widgets.showText': 'Mostrar el texto de la promesa',
  'widgets.privateDetail':
    'El texto de tu promesa se queda en Menta. Solo se muestran tu racha y tu progreso.',
  'widgets.publicDetail':
    'Visible para quien pueda ver tu pantalla de inicio. Desactívalo para mostrar solo tu progreso.',
  'widgets.howToAdd': 'Cómo añadirlo',
  'widgets.notNow': 'Ahora no',
  'widgets.instructions': 'Mira tu racha cada vez que desbloquees.',
  'widgets.instructionsDetail':
    'Añade Menta desde la galería de widgets de tu dispositivo.',
  'widgets.step1': 'Mantén pulsado',
  'widgets.step1Detail':
    'Mantén pulsada una zona vacía de la pantalla de inicio hasta que las apps se muevan.',
  'widgets.step2': 'Busca Menta',
  'widgets.step2Detail':
    'Toca Editar y luego Añadir widget (o toca +). Busca Menta.',
  'widgets.step3': 'Elige el tamaño',
  'widgets.step3Detail':
    'Elige un tamaño, toca Añadir widget y luego OK. Para la pantalla bloqueada, mantenla pulsada, elige Personalizar y luego Añadir widgets.',
  'widgets.gotIt': 'Entendido',
  'widgets.preview': 'Vista previa del widget',
  'widgets.loading': 'Cargando tus promesas',
  'widgets.retry': 'Reintentar',
  'widgets.error': 'No se ha podido actualizar tu widget. Inténtalo de nuevo.',
  'widgets.saveError':
    'No se ha podido guardar tu preferencia. Inténtalo de nuevo antes de salir de esta pantalla.',
  'widgets.unavailable':
    'Los widgets necesitan la versión más reciente de Menta para iPhone o iPad.',
  'widgets.inviteDetail':
    'Ve tu racha y tu próximo paso en tu pantalla de inicio.',
  'widgets.seeWidget': 'Ver el widget',
  'widgets.dismiss': 'Descartar la sugerencia del widget',
  'widgets.history': 'Pruebas recientes',
  'widgets.history.approved': 'Aceptada',
  'widgets.history.pending': 'Pendiente de revisión',
  'widgets.history.rejected': 'Necesita corrección',
  'widgets.state.due.heading': 'Sigue así.',
  'widgets.state.due.detail':
    'Hoy todavía necesita prueba antes de {deadline}.',
  'widgets.state.due.action': 'Añadir la prueba de hoy',
  'widgets.state.risk.heading': 'Aún estás a tiempo.',
  'widgets.state.risk.detail': 'Añade la prueba antes de {deadline}.',
  'widgets.state.risk.action': 'Añadir prueba ahora',
  'widgets.state.waiting.heading': 'Prueba enviada.',
  'widgets.state.waiting.detail':
    'Hoy aún no cuenta. Alguien tiene que aceptar la prueba.',
  'widgets.state.waiting.action': 'Ver tu prueba',
  'widgets.state.accepted.heading': 'Has seguido adelante.',
  'widgets.state.accepted.detail': 'La prueba de hoy está aceptada.',
  'widgets.state.accepted.action': 'Ver tu progreso',
  'widgets.state.protected.heading': 'Racha protegida.',
  'widgets.state.protected.detail':
    'Un protector de racha cubrió un día perdido.',
  'widgets.state.protected.action': 'Añadir la prueba de hoy',
  'widgets.state.correction.heading': 'Una pequeña corrección.',
  'widgets.state.correction.detail': 'Tu prueba necesita una corrección.',
  'widgets.state.correction.action': 'Corregir tu prueba',
  'widgets.state.missed.heading': 'Vuelve a empezar hoy.',
  'widgets.state.missed.detail': 'Tu próximo paso sigue contando.',
  'widgets.state.missed.action': 'Añadir la prueba de hoy',
  'widgets.state.empty.heading': 'Empieza con una promesa.',
  'widgets.state.empty.detail': 'Elige algo que quieras hacer.',
  'widgets.state.empty.action': 'Elegir una promesa',
  'widgets.state.signed-out.heading': 'Tu próxima promesa empieza aquí.',
  'widgets.state.signed-out.detail': 'Inicia sesión para ver tu racha.',
  'widgets.state.signed-out.action': 'Abrir Menta',
  'widgets.state.stale.heading': 'Veamos qué viene ahora.',
  'widgets.state.stale.detail': 'Abre Menta para ver tu racha actual.',
  'widgets.state.stale.action': 'Abrir Menta para actualizar',
  'widgets.state.choose.heading': 'Dale un lugar a tu racha.',
  'widgets.state.choose.detail': 'Elige una promesa en Menta.',
  'widgets.state.choose.action': 'Elegir tu promesa',
  'widgets.timeLeft.hours': 'quedan {hours} h',
  'widgets.timeLeft.minutes': 'quedan {minutes} min',
  'widgets.status.accepted': 'Hecho hoy',
  'widgets.status.waiting': 'Enviada · en revisión',
  'widgets.status.missed': 'Hoy es el día 1',
  'widgets.status.protected': 'Racha protegida',
  'widgets.status.correction': 'Necesita un ajuste',
} as const satisfies Record<keyof typeof widgetsEnNZ, string>;
