import type { widgetsEnNZ } from '../en-NZ/widgets';

export const widgetsfr = {
  'widgets.title': 'Widget de l’écran d’accueil',
  'widgets.entryDetail': 'Votre série et la prochaine étape en un coup d’œil.',
  'widgets.choose': 'Choisir votre widget',
  'widgets.heading': 'Gardez votre série en vue.',
  'widgets.subtitle': 'Un petit rappel pour continuer demain.',
  'widgets.promise': 'Promesse',
  'widgets.privatePromise': 'Votre promesse',
  'widgets.dayStreak': 'jours de suite',
  'widgets.today': 'Aujourd’hui',
  'widgets.beforeDeadline': 'Avant {deadline}',
  'widgets.showText': 'Afficher le texte de la promesse',
  'widgets.privateDetail':
    'Le texte de votre promesse reste dans Menta. Seuls votre série et vos progrès sont affichés.',
  'widgets.publicDetail':
    'Visible par toute personne pouvant voir votre écran d’accueil. Désactivez cette option pour n’afficher que vos progrès.',
  'widgets.howToAdd': 'Comment l’ajouter',
  'widgets.notNow': 'Pas maintenant',
  'widgets.instructions': 'Voyez votre série à chaque déverrouillage.',
  'widgets.instructionsDetail':
    'Ajoutez Menta depuis la galerie de widgets de votre appareil.',
  'widgets.step1': 'Appuyez longuement',
  'widgets.step1Detail':
    'Sur l’écran d’accueil, appuyez longuement sur une zone vide jusqu’à ce que les apps s’animent.',
  'widgets.step2': 'Trouvez Menta',
  'widgets.step2Detail':
    'Touchez Modifier, puis Ajouter un widget (ou +). Recherchez Menta.',
  'widgets.step3': 'Choisissez la taille',
  'widgets.step3Detail':
    'Choisissez une taille, touchez Ajouter le widget, puis OK. Pour l’écran verrouillé, appuyez longuement dessus, puis choisissez Personnaliser et Ajouter des widgets.',
  'widgets.gotIt': 'Compris',
  'widgets.preview': 'Aperçu du widget',
  'widgets.loading': 'Chargement de vos promesses',
  'widgets.retry': 'Réessayer',
  'widgets.error': 'Impossible d’actualiser votre widget. Réessayez.',
  'widgets.saveError':
    'Impossible d’enregistrer votre préférence. Réessayez avant de quitter cet écran.',
  'widgets.unavailable':
    'Les widgets nécessitent la dernière version de Menta pour iPhone ou iPad.',
  'widgets.inviteDetail':
    'Retrouvez votre série et la prochaine étape sur votre écran d’accueil.',
  'widgets.seeWidget': 'Voir le widget',
  'widgets.dismiss': 'Fermer la suggestion de widget',
  'widgets.history': 'Preuves récentes',
  'widgets.history.approved': 'Acceptée',
  'widgets.history.pending': 'En attente de validation',
  'widgets.history.rejected': 'Correction nécessaire',
  'widgets.state.due.heading': 'Continuez comme ça.',
  'widgets.state.due.detail':
    'Un jour de plus commence par votre prochain pas.',
  'widgets.state.due.action': 'Ajouter la preuve du jour',
  'widgets.state.risk.heading': 'Il est encore temps.',
  'widgets.state.risk.detail': 'Ajoutez votre preuve avant {deadline}.',
  'widgets.state.risk.action': 'Ajouter une preuve maintenant',
  'widgets.state.waiting.heading': 'Preuve envoyée.',
  'widgets.state.waiting.detail': 'En attente de validation.',
  'widgets.state.waiting.action': 'Voir votre preuve',
  'widgets.state.accepted.heading': 'Vous avez continué.',
  'widgets.state.accepted.detail': 'La preuve du jour est acceptée.',
  'widgets.state.accepted.action': 'Voir vos progrès',
  'widgets.state.protected.heading': 'Série protégée.',
  'widgets.state.protected.detail': 'Une protection a couvert un jour manqué.',
  'widgets.state.protected.action': 'Ajouter la preuve du jour',
  'widgets.state.correction.heading': 'Une petite correction.',
  'widgets.state.correction.detail': 'Votre preuve doit être corrigée.',
  'widgets.state.correction.action': 'Corriger votre preuve',
  'widgets.state.missed.heading': 'Recommencez dès aujourd’hui.',
  'widgets.state.missed.detail': 'Votre prochain pas compte toujours.',
  'widgets.state.missed.action': 'Ajouter la preuve du jour',
  'widgets.state.empty.heading': 'Commencez par une promesse.',
  'widgets.state.empty.detail':
    'Choisissez quelque chose que vous voulez faire.',
  'widgets.state.empty.action': 'Choisir une promesse',
  'widgets.state.signed-out.heading': 'Votre prochaine promesse commence ici.',
  'widgets.state.signed-out.detail': 'Connectez-vous pour voir votre série.',
  'widgets.state.signed-out.action': 'Ouvrir Menta',
  'widgets.state.stale.heading': 'Voyons la prochaine étape.',
  'widgets.state.stale.detail': 'Ouvrez Menta pour voir votre série actuelle.',
  'widgets.state.stale.action': 'Ouvrir Menta pour actualiser',
  'widgets.state.choose.heading': 'Offrez une place à votre série.',
  'widgets.state.choose.detail': 'Choisissez une promesse dans Menta.',
  'widgets.state.choose.action': 'Choisir votre promesse',
  'widgets.timeLeft.hours': 'encore {hours} h',
  'widgets.timeLeft.minutes': 'encore {minutes} min',
  'widgets.status.accepted': 'Fait aujourd’hui',
  'widgets.status.waiting': 'Envoyée · en vérification',
  'widgets.status.missed': 'Jour 1 aujourd’hui',
  'widgets.status.protected': 'Série protégée',
  'widgets.status.correction': 'Une correction à faire',
} as const satisfies Record<keyof typeof widgetsEnNZ, string>;
